version: '1.0'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
      TOKEN_SECRET: your_token_secret
      MONGODB_URL: mongodb://mongo:27017/
      CORS_ORIGIN: http://localhost:4000
      METRICS_PASSWORD: your_metrics_password
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis
      - prometheus
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
